### ISSUE TITLE
Click on timestamp change short

### ISSUE THREAD

**Issue by Luke0094** [ynshung/better-yt-shorts#145] opened 2023-10-07 08:03 UTC
If you press on on timestamp it actually cause various effect
1) timestamp not accurate skipping frame, at third time supposedly crash
2) changing short and then using timestamp will change short based on list position.

**Comment by luchettodj94** [comment] 2023-10-08 23:35
By inspecting a bit more this behaviour seem the timing of various short is overlapping and you'll get with with more than 60sec connecting various shorts.
Somehow I think yt is at fault here since sometimes you'll get 1 frame of the next short before repeating itself (or is a problem with the autoplay, idk)

**Comment by luchettodj94** [comment] 2023-10-12 01:05
I guess the problem is fixed now, not sure if the extension got update or chromium version however everything is working again fine.

**Comment by adsuth** [comment] 2023-10-25 14:59
linking this to #149 because I'm still getting this

**Comment by ynshung** [comment] 2023-12-08 17:17
Closing at it seems to be fixed for now, let me know if it is still occurring

**Closed** 2023-12-10 06:38 UTC
Labels: bug, major
