### ISSUE TITLE
Increasing speed with key press can go beyond 2x

### ISSUE THREAD

**Issue by nm004** [ynshung/better-yt-shorts#138] opened 2023-10-04 13:29 UTC
### System Information
Extension version: 3.0.1
Web browser: Firefox 118

### Issue description
First, thank you for your good work.

I found that if I press a key to increase the playback speed, it can go up to 16x speed. I expect that pressing a key goes back to 0.5x from 2.0x as a clicking a speed button does.

I also found that pressing a key and clicking a button have different speed ups and downs: +-0.25 for pressing a key, on the other hand, +0.5 for clickng a button.

**Comment by ynshung** [comment] 2023-10-04 13:48
Hello there, for the 16x speed it is an intended behavior since increasing speed shouldn't really get you back to the slowest. This can also be done also by scrolling on the speed indicator.

Speaking of 16x speed it was first added in the first build since there isn't any reason not to add into it. But I believe we can limit the speed to 4x/6x/8x as I don't think a lot of users watch shorts with such a great playback rate. But maybe there is a small minority who does?

For the different speed changes for pressing key and clicking the speed button, I suppose we can standardize the speed increment by 0.25 for both. @adsuth I think we can do that?

**Comment by nm004** [comment] 2023-10-04 14:10
Thank you for your reply and good clarification.

> Hello there, for the 16x speed it is an intended behavior since increasing speed shouldn't really get you back to the slowest. This can also be done also by scrolling on the speed indicator.

I did not know that wheel can change the playback speed. Thank you letting me know.

> Speaking of 16x speed it was first added in the first build since there isn't any reason not to add into it. But I believe we can limit the speed to 4x/6x/8x as I don't think a lot of users watch shorts with such a great playback rate. But maybe there is a small minority who does?

Thanks to that, we can watch super speed shorts B)

> For the different speed changes for pressing key and clicking the speed button, I suppose we can standardize the speed increment by 0.25 for both. @adsuth I think we can do that?

Although I pointed it out, I feel it shoud stay the way it is now because if the step becomes 0.25, users must click twice as many as they currently do. I think the wheel scroll is the best way to scratch that itch.

**Comment by ynshung** [comment] 2023-10-04 14:23
Thank you for the input! I think we will stay the current way for now. Closing this for now, let us know if have anymore suggestion :D

**Closed by ynshung** 2023-10-04 14:23 UTC
