### ISSUE TITLE
Youtube removed the view counter, please add it back!

### ISSUE THREAD

**Issue by Shadownite64** [ynshung/better-yt-shorts#176] opened 2023-11-21 09:03 UTC
Recently youtube made a change to shorts in which views were removed from the shorts description page, it used to show how many views the short got, but yet again youtube removed another statistic counter that some people may want to know, whats worse is that if you dig through the creators channel to find the short you JUST WATCHED, you can see how many views it got, can you please add the view counter back in the description on shorts or at least have it on the video like with the upload date.

![image](https://github.com/ynshung/better-yt-shorts/assets/68400080/d51d4011-c036-4172-bff8-d71f291be74a)

**Comment by adsuth** [comment] 2023-11-22 12:24
It isnt feasible (or at least, not in the scope of this project) to add a view count unless its somewhere on the page.

Though maybe its just been moved and is still present. Worth looking into

**Comment by adsuth** [comment] 2023-11-22 12:25
actually I'm pretty sure this is a duplicate of #173

**Closed** 2023-11-22 13:21 UTC
Labels: duplicate, question
